name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: nuxt/actions-yarn@master
      - run: "yarn install"
      - run: "yarn lint"
